[build]
  functions = "functions_build"
  
[[redirects]]
  from = "/api"
  to = "/.netlify/functions/api"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"