[build]
  functions = "functions_build"
  
[[redirects]]
  from = "/api"
  to = "/.netlify/functions/api"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Origin = "*"